"""
upgrade_tier3_and_fix.py
========================
Two-pass enrichment of gpr_globalplantdb.csv:

Pass 1 — Tier 3 upgrade
  For every Tier 4 species whose genus has at least one Tier 1 or Tier 2
  measurement, compute genus-mean LAI from the measured species and promote
  the Tier 4 record to Tier 3.

Pass 2 — ai_assisted correction
  Sets ai_assisted = False for ALL records.
  Rationale: no LAI values in this database were generated by an AI model.
  Tier 4 values derive from Bonan (2008) PFT means applied via Python script.
  Claude (Anthropic) was used only to write the Python scripts; it did not
  generate data values. This distinction is critical for Scientific Data
  peer review.

Output: gpr_globalplantdb_enriched.csv  (CSV only — Supabase upload is a
        separate step requiring explicit approval)

Author: Boon Lay Ong / GPRI  |  Script assisted by Claude (Anthropic)
Run:    python upgrade_tier3_and_fix.py
"""

import sys
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import csv
import math
from pathlib import Path
from datetime import date
from collections import defaultdict

BASE = Path(r"C:\_myProjects\+GPR\GPRTool\lai")
IN_CSV  = BASE / "gpr_globalplantdb.csv"
OUT_CSV = BASE / "gpr_globalplantdb_enriched.csv"
TODAY   = date.today().isoformat()

# ── Load ─────────────────────────────────────────────────────────────────────

print("Loading database...")
with open(IN_CSV, encoding="utf-8") as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    rows = list(reader)

print(f"  {len(rows):,} rows loaded")

# ── Pass 1: Build genus means from Tier 1 and Tier 2 ─────────────────────────

print("\nPass 1 — computing genus means from Tier 1/2 data...")

genus_data = defaultdict(list)  # genus -> list of (lai_mean, lai_min, lai_max)

for row in rows:
    if row.get('tier') in ('1', '2'):
        genus = row['species'].split()[0] if row.get('species') else None
        if not genus:
            continue
        try:
            lai_mean = float(row['lai_mean'])
            lai_min  = float(row['lai_min'])  if row.get('lai_min')  else lai_mean
            lai_max  = float(row['lai_max'])  if row.get('lai_max')  else lai_mean
            genus_data[genus].append((lai_mean, lai_min, lai_max))
        except (ValueError, TypeError):
            pass

# Compute genus statistics
genus_stats = {}
for genus, vals in genus_data.items():
    means = [v[0] for v in vals]
    mins  = [v[1] for v in vals]
    maxs  = [v[2] for v in vals]
    n = len(vals)
    g_mean = round(sum(means) / n, 3)
    g_min  = round(min(mins), 3)
    g_max  = round(max(maxs), 3)
    # Standard deviation
    if n > 1:
        variance = sum((m - g_mean) ** 2 for m in means) / (n - 1)
        g_sd = round(math.sqrt(variance), 3)
    else:
        g_sd = ''
    genus_stats[genus] = {
        'lai_mean': g_mean,
        'lai_min':  g_min,
        'lai_max':  g_max,
        'lai_sd':   g_sd,
        'n':        n
    }

print(f"  {len(genus_stats):,} genera with measured LAI data")

# ── Pass 1: Apply genus means to upgradeable Tier 4 rows ─────────────────────

upgraded = 0
for row in rows:
    if row.get('tier') != '4':
        continue
    genus = row['species'].split()[0] if row.get('species') else None
    if not genus or genus not in genus_stats:
        continue

    gs = genus_stats[genus]
    row['tier']        = '3'
    row['tier_source'] = 'Genus_Mean'
    row['lai_mean']    = str(gs['lai_mean'])
    row['lai_min']     = str(gs['lai_min'])
    row['lai_max']     = str(gs['lai_max'])
    row['lai_sd']      = str(gs['lai_sd'])
    row['lai_n']       = str(gs['n'])
    row['lai_method']  = 'genus-mean'
    row['lai_context'] = 'inferred'
    row['sources']     = (
        f"Genus mean derived from {gs['n']} measured species in ORNL DAAC "
        f"(Scurlock et al. 2001) and/or TRY Database (Kattge et al. 2020). "
        f"See Tier 1/2 records for genus {genus}."
    )
    row['notes'] = (
        f"LAI inferred from genus mean of {gs['n']} measured congener(s). "
        f"Mean={gs['lai_mean']}, Min={gs['lai_min']}, Max={gs['lai_max']}. "
        f"Apply with caution; species-level variation may be substantial."
    )
    row['entry_date']    = TODAY
    row['data_version']  = '1.1.0'
    upgraded += 1

print(f"  {upgraded:,} Tier 4 records upgraded to Tier 3")

# ── Pass 2: Fix ai_assisted for ALL rows ─────────────────────────────────────

print("\nPass 2 — correcting ai_assisted field...")

corrected = 0
for row in rows:
    if row.get('ai_assisted') in ('True', 'TRUE', 'true', True):
        row['ai_assisted'] = 'False'
        row['ai_model']    = ''
        corrected += 1

print(f"  {corrected:,} records corrected (ai_assisted: True → False)")
print(f"  Rationale: all LAI values derive from published measured sources or")
print(f"  documented PFT equations (Bonan 2008). Claude was used to write")
print(f"  Python scripts only — not to generate data values.")

# ── Update data_version for upgraded rows ────────────────────────────────────

# Already done above for Tier 3 upgrades; update Tier 4 remainder too
for row in rows:
    if row.get('data_version') == '1.0.0':
        row['data_version'] = '1.1.0'

# ── Write output ─────────────────────────────────────────────────────────────

print(f"\nWriting {OUT_CSV.name}...")
with open(OUT_CSV, 'w', encoding='utf-8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"  Done — {len(rows):,} rows written")

# ── Summary report ───────────────────────────────────────────────────────────

tier_counts = {}
for row in rows:
    t = row.get('tier', 'unknown')
    tier_counts[t] = tier_counts.get(t, 0) + 1

print("\n" + "="*50)
print("DATABASE ENRICHMENT SUMMARY — v1.1.0")
print("="*50)
print(f"Total species:          {len(rows):>8,}")
for t in sorted(tier_counts.keys()):
    label = {
        '1': 'Tier 1 — Urban field measured',
        '2': 'Tier 2 — Open-ground measured',
        '3': 'Tier 3 — Genus mean (inferred)',
        '4': 'Tier 4 — PFT mean (inferred)',
    }.get(t, f'Tier {t}')
    print(f"  {label:<35} {tier_counts[t]:>8,}")
print(f"\nTier 3 records added:   {upgraded:>8,}")
print(f"ai_assisted corrected:  {corrected:>8,}")
print(f"Output file:            {OUT_CSV.name}")
print(f"Next step:              Run enrich_koppen.py --all to populate")
print(f"                        gbif_taxon_key and native_region via GBIF API")
print(f"                        (~2.5 hrs for full database)")
print(f"Then:                   Run upload_to_supabase.py on enriched CSV")
print("="*50)
